### ISSUE TITLE
library "teach: ?No such file or directory

### ISSUE THREAD

**Issue by m-bob** [danlm/QNial7#5]
Hi!

Thanks so much for making this! I'm not currently nt trying to build Nial; I've just downloaded the binaries to play with the language. The examples seem to run, except for library "teach, which gives the error above. I've tried to systematically search through the files here to see if I can find/recognize it, but I haven't found anything that looks promising.

Can you help?

Thanks!

Murray

**Comment by gibbonsja** [comment]
Hi Murray,

Could you tell me which system you are running on and also send me the value of Nialroot on your system. Just run nial interactively and then type Nialroot at the prompt.

The teach code uses the value of Nialroot to find the 'tutorial' directory on your system. 

Right at the bottom of the 'teach.ndf' file in the directory niallib there is a line

Filepath := link NialRoot Os_Path_Separator 'tutorial' Os_Path_Separator (string Filename) '.dat';

It sounds like your Nialroot (nial is not case sensitive) is not right for where you have installed the Nial system.

John
(gibbons.ja@gmail.com)

**Comment by m-bob** [comment]
Hi John,

Thank you so much! 'Nialroot' for me turned out to be the (nonexistent)
directory ~/QNial7/Nialroot.

I created that directory, moved the nial binary there, copied the folders
niallib and tutorial there, and modified my path variable to include the
Nialroot directory (so the nial binary could be easily accessed).

That all works fine and the nial finds the tutorial. Again, thanks!

Before your reply, I had not gone through the build process. I had just
copied the binaries. After you wrote, I decided to try the full build
process. It worked very smoothly. (Actually I went through the build
process twice. After the first build, I decided to add the fft, audio, and
dsp modules. I installed the required libraries and set the appropriate
environment variables. The audio and dsp modules built correctly. The fft
module was more trouble -- it couldn't find the fftw3.h file or-lfftw3
despite the environment variables telling it where to look. I eventually
got around that problem.)

I have two new questions:

[1] Is there any documentation (or examples) for the fft, audio, and dsp
extensions?
[2] In an earlier nial version I was able to use the (somewhat damaged)
ISIJ.ttf font to get very clean looking boxes around arrays. (But all was
not perfect. Using the ISIJ font led to other issues.) Is there any way to
get nice-looking boxes (using either ascii or utf box-drawing characters)
using the current version?

I'm quite a nial novice. I've admired the language from afar for some time,
and played with it a tiny bit, but I haven't yet taken the plunge to more
fully explore it. I hope to be able to do so soon.

BTW, I'm using Mac OS X 10.15.7 (Catalina) on an old Macbook Pro laptop. I
use brew to install the supporting libraries. I plan to bypass Big Sur and
move to Monterey when it's released (assuming my laptop will support it).

I am very much grateful for you making nial available and for your help!

Yours,

Murray

**Comment by gibbonsja** [comment]
Hi Murray,

 I have had a look at the display code for arrays etc. At the moment the
code is just using the basic ascii characters that you see when you display
an array. There is some initialisation code in picture.c that sets the
codes to be used for the different box characters. At the moment there are
two sets of characters, the basic ascii and an IBM extended character set
and the default set is the basic ascii. This can be changed in the startup
code by changing the parameter to 'initboxchars' . I havent tries this yet.
We also should be able to use unicode chars in utf-8 so I will look at
that.

The dsp, fftw code was originally added to support Stu Smith who waa
building a library for audio manipulation. I will try to get that to you.

John

**Comment by m-bob** [comment]
Thanks, John! After you've done so much already, it's rather presumptuous
of me to ask for more, but I really appreciate what you're doing!

Again, thank you!

Murray

**Comment by m-bob** [comment]
Thanks!
